---
- name: install accessory apps and fonts
  become: yes
  apt:
    name:
      # Text editor
      - gedit
      # Seahorse SSH agent GUI
      - seahorse-daemon
      # Evince PDF viewer
      - evince
      # Gnome Calculator
      - gnome-calculator
      # Meld - Diff/Merge tool
      - meld
      # Git-GUI graphical Git client
      - git-gui
      # Emoji font
      - fonts-noto-color-emoji
      # Monospaced font with programming ligatures
      - fonts-firacode
      # Liberation fonts (Fonts with the same metrics as Times, Arial and Courier)
      - fonts-liberation
      # OpenSymbol fonts
      - fonts-opensymbol
      # Scientific and Technical Information eXchange fonts
      - fonts-stix
    state: present
