---
- name: install accessory apps
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    # Text editor
    - gedit
    # Seahorse SSH agent GUI
    - seahorse-daemon
    # Evince PDF viewer
    - evince
    # Gnome Calculator
    - gnome-calculator
    # Meld - Diff/Merge tool
    - meld
