---
- name: install accessory apps and fonts
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    # Text editor
    - gedit
    # Seahorse SSH agent GUI
    - seahorse-daemon
    # Evince PDF viewer
    - evince
    # Gnome Calculator
    - gnome-calculator
    # Meld - Diff/Merge tool
    - meld
    # Liberation fonts (Fonts with the same metrics as Times, Arial and Courier)
    - fonts-liberation
    # OpenSymbol fonts
    - fonts-opensymbol
    # Scientific and Technical Information eXchange fonts
    - fonts-stix
