---
- name: install fonts
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    # Liberation fonts (Fonts with the same metrics as Times, Arial and Courier)
    - fonts-liberation
    # OpenSymbol fonts
    - fonts-opensymbol
    # Scientific and Technical Information eXchange fonts
    - fonts-stix
