---
- name: install ubuntu-desktop
  become: yes
  apt:
    name:
      - ubuntu-desktop
      # Archive manager
      - file-roller
      # TaskManager equivalent
      - gnome-system-monitor
    state: present
    install_recommends: no
