# code: language=ansible
---
- name: Install ubuntu-desktop
  become: true
  ansible.builtin.apt:
    name:
      - ubuntu-desktop
      # Archive manager
      - file-roller
      # TaskManager equivalent
      - gnome-system-monitor
      # Install theme
      - yaru-theme-gtk
      - yaru-theme-sound
      - yaru-theme-gnome-shell
      - yaru-theme-icon
      - yaru-theme-unity
    state: present
    install_recommends: false
