---
- name: install ubuntu-desktop
  become: yes
  apt:
    name:
      - ubuntu-desktop
      # Archive manager
      - file-roller
      # TaskManager equivalent
      - gnome-system-monitor
      # Install theme
      - yaru-theme-gtk
      - yaru-theme-sound
      - yaru-theme-gnome-shell
      - yaru-theme-icon
      - yaru-theme-unity
    state: present
    install_recommends: no
