---
- name: assert desktop environment in supported list
  assert:
    that:
      - "xdesktop_desktop in ('unity', 'xfce4')"

- include: unity-desktop.yml
  when: xdesktop_desktop == 'unity'

- include: xfce4-desktop.yml
  when: xdesktop_desktop == 'xfce4'

- include: fonts.yml

- include: accessories.yml
