---
- name: assert desktop environment in supported list
  assert:
    that:
      - "xdesktop_desktop in ('unity', 'xfce4')"

- include_tasks: '{{ xdesktop_desktop }}-desktop.yml'

- import_tasks: accessories.yml
