# code: language=ansible
---
- name: Install xz-utils
  become: true
  ansible.builtin.apt:
    name: xz-utils

- name: Create download directory
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ xdesktop_download_dir }}'

- name: Download Nerd Font
  ansible.builtin.get_url:
    url: '{{ xdesktop_nerd_font_redis_url }}'
    checksum: 'sha256:{{ xdesktop_nerd_font_redis_sha256sum }}'
    dest: '{{ xdesktop_download_dir }}/{{ xdesktop_nerd_font_local_filename }}'
    force: false
    mode: 'u=rw,go=r'

- name: Create font directory
  become: true
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,g=rwxs,o=rx'
    dest: '{{ xdesktop_font_install_directory }}'

- name: Install Nerd Font
  become: true
  ansible.builtin.unarchive:
    src: '{{ xdesktop_download_dir }}/{{ xdesktop_nerd_font_local_filename }}'
    remote_src: true
    dest: '{{ xdesktop_font_install_directory }}'
    include: '{{ xdesktop_nerd_font_install_files }}'
    mode: 'ug=rw,o=r'
    owner: root
    group: staff
  notify: Update font-cache

- name: Write monospace font config
  become: true
  ansible.builtin.template:
    src: monospace_font.gschema.override.j2
    dest: '{{ xdesktop_glib_schemas_directory }}/20_ansible_monospace_font.gschema.override'
    owner: root
    group: root
    mode: 'u=rw,go=r'
  notify: 'X-Desktop: apply glib schemas changes'
