---
- name: install ubuntu-desktop
  become: yes
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - ubuntu-desktop
    # Without this the application menu doesn't work
    - unity-lens-applications
