---
- name: add dockbarx ppa
  become: yes
  apt_repository:
    repo: 'ppa:dockbar-main/ppa'

- name: install xubuntu
  become: yes
  apt:
    name:
      - xubuntu-core
      - xfce4-taskmanager
      - thunar-archive-plugin
      - dockbarx
      - xfce4-dockbarx-plugin
    state: present

# Remove screensaver (host OS has screensaver)
- name: uninstall xscreensaver
  become: yes
  apt:
    name: xscreensaver
    state: absent
