---
- name: create xfce4 config directory
  file:
    path: "/home/{{ item.username }}/.config/xfce4/xfconf/xfce-perchannel-xml"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  with_items: "{{ users }}"

- name: write xfce4 power manager config
  template:
    src: xfce4-power-manager.xml
    dest: "/home/{{ item.username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  with_items: "{{ users }}"

- name: write xfce4 panel config
  template:
    src: xfce4-panel.xml
    dest: "/home/{{ item.username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  with_items: "{{ users }}"
