---
- name: create custom config directory
  become: yes
  file:
    path: "{{ xdesktop_xfce4_custom_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: create Xsession.d directory
  become: yes
  file:
    path: "{{ xdesktop_xsession_d_dir }}"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: write Xsession config
  become: yes
  template:
    src: x-session.j2
    dest: '{{ xdesktop_xsession_d_dir }}/70-ansible-xdesktop'
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: create xfce4 perchannel config directory
  become: yes
  file:
    path: "{{ xdesktop_xfce4_custom_config_dir }}/xfce4/xfconf/xfce-perchannel-xml"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: write xfce4 power manager config
  become: yes
  template:
    src: xfce4-power-manager.xml.j2
    dest: "{{ xdesktop_xfce4_custom_config_dir }}/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: create xfce4 panel config directory
  become: yes
  file:
    path: "{{ xdesktop_xfce4_custom_config_dir }}/xfce4/panel"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: write xfce4 panel config
  become: yes
  template:
    src: xfce4-panel.xml.j2
    dest: "{{ xdesktop_xfce4_custom_config_dir }}/xfce4/panel/default.xml"
    owner: root
    group: root
    mode: 'u=rw,go=r'
