---
- name: 'X-Desktop: apply glib schemas changes'
  become: true
  ansible.builtin.command: '/usr/bin/glib-compile-schemas {{ xdesktop_glib_schemas_directory }}'

- name: Update font-cache
  become: true
  ansible.builtin.command: fc-cache -fv
