---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no

  roles:
    - role: ansible-role-xdesktop
      xdesktop_desktop: gnome
