---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test_usr
      become: yes
      user:
        name: test_usr
        state: present
        home: /home/test_usr
        createhome: yes

  roles:
    - role: ansible-role-xdesktop
    - role: ansible-role-xdesktop
      xdesktop_desktop: xfce4
